### ISSUE TITLE
Deploy NSX Container Plugin (NCP) is not working

### ISSUE THREAD

**Issue by joungwoongpark** [dumlutimuralp/nsx-t-k8s#1]
Hi. I followed your k8s-with-nsx-t-2.4.x manual.
but there is a problem. 
it happened when I deployed NCP. 
After Inputing Command and Checking kubectl get pods --all-namespaces
the pods is crashloopbackoff.
I don't know the reason, 

here is my NCP.yml
[ncp-deployment-custom.yml_1.txt](https://github.com/dumlutimuralp/k8s-with-nsx-t-2.4.x/files/4002249/ncp-deployment-custom.yml_1.txt)

**Comment by dumlutimuralp** [comment]
Have you checked the NCP pod logs with "kubectl logs <ncp pod id> -n nsx-system" ? Usually that helps most of the time cause the log messages are pretty explanatory.
